
export const SOCKETIO_STORE_PREFIX = 'SOCKET_'

export const SOCKETIO_CONNECTED = `${SOCKETIO_STORE_PREFIX}connect`
export const SOCKETIO_DISCONNECTED = `${SOCKETIO_STORE_PREFIX}disconnect`

export const SOCKETIO_USER_RENAMED = `${SOCKETIO_STORE_PREFIX}USER_RENAMED`
export const SOCKETIO_USER_UPDATED = `${SOCKETIO_STORE_PREFIX}USER_UPDATED`
export const SOCKETIO_ERROR = `${SOCKETIO_STORE_PREFIX}ERROR`
export const SOCKETIO_ROOM_JOINED = `${SOCKETIO_STORE_PREFIX}ROOM_JOINED`
export const SOCKETIO_ROOM_USER_JOINED = `${SOCKETIO_STORE_PREFIX}ROOM_USER_JOINED`
export const SOCKETIO_ROOM_USER_LEFT = `${SOCKETIO_STORE_PREFIX}ROOM_USER_LEFT`
export const SOCKETIO_ROOM_USER_RENAMED = `${SOCKETIO_STORE_PREFIX}ROOM_USER_RENAMED`
